### ISSUE TITLE
it doesn't work under Windows

### ISSUE THREAD

**Issue by jabbalaci** [bokwoon95/wgo#1]
I tried it under Linux and Windows. Under Linux, it works as expected. However, under Windows 10 it doesn't seem to work. It doesn't notice when my file was changed. My command: `wgo -file=.Rmd make all` . When I modify an `.Rmd` file and save it, nothing happens, wgo is just waiting. I also tried it in a simplified way: `wgo -file=.Rmd echo hello`, the result was the same. `pwsh.exe` is available.

**Comment by bokwoon95** [comment]
If you run it with -verbose, does it show your file was detected?

**Comment by jabbalaci** [comment]
I tried it on a native Windows 10 too and it works there. The Windows, where it doesn't want to work, is running in a virtual machine (with VirtualBox).

**Comment by bokwoon95** [comment]
Oof yeah the file notification library I'm using generally doesn't work on network drives (or Docker). I'm guessing VirtualBox doesn't trigger native OS file events as well. Were you using VirtualBox on Linux as well?

**Comment by jabbalaci** [comment]
My host system is Linux, there it works well.

My guest system is Windows. Here:
* on drive C:, it works well
* However, I have a folder that is shared between the host and the guest and it's mounted as a network drive. There, under Windows (in the guest), wgo doesn't work.

**Comment by bokwoon95** [comment]
I'm thinking of adding a polling solution to combat this (by [copying the implementation from Hugo](https://github.com/gohugoio/hugo/commit/24ce98b6d10b2088af61c15112f5c5ed915a0c35)).

**Comment by gadiener** [comment]
I'd also be interested in the polling solution. I have a similar problem when running wgo in Docker on Mac

**Comment by bokwoon95** [comment]
This has been a long time, but I've added support for [polling files](https://github.com/bokwoon95/wgo#use-polling-to-detect-file-changes) to wgo.
