### ISSUE TITLE
option to control signal (or number of signals)

### ISSUE THREAD

**Issue by tmc** [bokwoon95/wgo#4]
Since some programs have graceful shutdowns, it's possible that the previous program (with a bound port perhaps) isn't done stopping by the time wgo starts the next process. 

Please consider supplying the ability to send multiple signals or control which signal is sent.

**Comment by bokwoon95** [comment]
> Please consider supplying the ability to send multiple signals or control which signal is sent.

What signals are you looking at? Currently [wgo uses SIGTERM](https://github.com/bokwoon95/wgo/blob/6ea3e5229882b3068841dcdbdbed3d424825443b/util_unix.go#L30) to kill the process, which applications can intercept and use it to initiate graceful shutdown. There's a sample program ([testdata/signal/main.go](https://github.com/bokwoon95/wgo/blob/6ea3e5229882b3068841dcdbdbed3d424825443b/testdata/signal/main.go)) that shows this in action, and the tests [signal off](https://github.com/bokwoon95/wgo/blob/6ea3e5229882b3068841dcdbdbed3d424825443b/wgo_cmd_test.go#L599-L620) and [signal on](https://github.com/bokwoon95/wgo/blob/6ea3e5229882b3068841dcdbdbed3d424825443b/wgo_cmd_test.go#L622-L646) test that program.

> it's possible that the previous program (with a bound port perhaps) isn't done stopping by the time wgo starts the next process

Oh, that should not be possible. wgo doesn't run the next command until the previous command is fully killed. Is there something you're observing that shows that it is happening?
