### ISSUE TITLE
create release builds

### ISSUE THREAD

**Issue by tommyo** [bokwoon95/wgo#9]
Can you create releases so that binaries can be installed without the go requirement?

If you do that, I will create an [asdf](https://asdf-vm.com/) plugin similar to what I did for [templ](https://github.com/tommyo/asdf-templ)

I would do it and submit a pull request, but I'm not that proficient in workflows.

**Comment by bokwoon95** [comment]
Closed by adding [https://github.com/bokwoon95/wgo/blob/main/.github/workflows/build.yml](https://github.com/bokwoon95/wgo/blob/main/.github/workflows/build.yml).
